**Задача 1.**

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [16]:
import math
def distance(x1: float, y1: float, x2: float, y2: float):
    return round(math.sqrt(math.pow(x1 - y1, 2) + math.pow(x2 - y2, 2)), 2)

x1 = float(input("Please enter x1: "))
y1 = float(input("Please enter y1: "))
x2 = float(input("Please enter x2: "))
y2 = float(input("Please enter y2: "))

print(f"({x1}, {y1}), ({x2}, {y2});\nDistance between two dots: ", distance(x1, y1, x2, y2))

(4.0, 8.5), (-6.0, 7.0);
Distance between two dots:  13.76


**Задача 2.**

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [25]:
s = ""

def season(month: int):
    global s
    match month:
        case 1 | 2 | 3:
            s = "Winter"
        case 4 | 5 | 6:
            s = "Spring"
        case 7 | 8 | 9:
            s = "Summer"
        case 10 | 11 | 12:
            s = "Winter"
        case _:
            s = "There is no such season..."

month = int(input("Please enter month number (1..12): "))
season(month)
print(f"The season is ... {s}")

The season is ... There is no such season...


**Задача 3.**

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [29]:
def is_prime(num: int):

    if (num == 0): # Число 0 не является ни простым,
        return;    # ни составным, но по условию задания входит
                   # в диапозон допустимых значений
    for i in range(2, int(math.sqrt(num))):
        if num % i == 0:
            return False
    return True

print(is_prime(0))
print(is_prime(1))
print(is_prime(13))
print(is_prime(24))

None
True
True
False


**Задача 4.**

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
- исходный список:  8, 1, 0, 4
- полученный список: 4, 0, 1, 8

Использовать встроенные функции Python нельзя. 

In [34]:
def reverse_list(arr: list):
    # можно сделать через срезы: arr[::-1]
    # можно по классике через цикл
    length = len(arr)
    for i in range(0, length // 2):
        arr[i], arr[length - i - 1] = arr[length - i - 1], arr[i]

    return arr

print(reverse_list([8, 1, 0, 4]))
print(reverse_list([1, 2, 3, 4, 5]))

[4, 0, 1, 8]
[5, 4, 3, 2, 1]


**Задача 5.**

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [44]:
print("Привет мир!"[3:8].upper())

ВЕТ М


**Задача 6.**

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [51]:
def reverse_odd_elements(arr: list):
    length = len(arr)
    x = 0
    if (length % 2 == 1):
        x = 1

    for i in range(1, length // 2, 2):
        arr[i], arr[length - i - x] = arr[length - i - x], arr[i]

    return arr

print(reverse_odd_elements([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
print(reverse_odd_elements([0, 1, 2, 3, 4, 5, 6, 7, 8]))

[0, 9, 2, 7, 4, 5, 6, 3, 8, 1]
[0, 7, 2, 5, 4, 3, 6, 1, 8]


**Задача 7.**

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [52]:
for i in range(0, 501):
    if (i % 7 == 0 and str(i).find("8") != -1):
        print(i)

28
84
98
168
182
189
238
280
287
308
378
385
448
483


**Задача 8.**

На вход функция more_than_five(lst) получает список из целых чисел. 
Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [53]:
def more_than_five(arr: list[int]):
    new_arr = []
    for i in arr:
        if (abs(i) > 10):
            new_arr.append(i)
    return new_arr

print(more_than_five([5, 7, 12, -5, -24, 11, 10, -10, -53, 3]))

[12, -24, 11, -53]


# Задания

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```

In [2]:
import numpy as np

size = 10

arr = np.zeros((size, size))

for i in range(0, size):
    arr[0, i] = 1
    arr[size - 1, i] = 1
    arr[i, 0] = 1
    arr[i, size - 1] = 1

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [197]:
arr = np.diag([1, 2, 3, 4], 1)
print(arr)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**Задача 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее.

In [131]:
rng = np.random.default_rng()

x = rng.integers(2, 8)
y = rng.integers(2, 8)
print(f"x={x}, y={y}")

arr = np.zeros((x,y))

for i in range(0, x):
    arr[i] = rng.integers(1,100, y)


print(arr, "\n")

for i in range(0, x):
    mean = round(arr[i].mean(), 2)
    arr[i] -= mean

print(arr)


x=4, y=7
[[75. 99. 88. 85. 89. 42. 85.]
 [ 1. 94.  6. 96. 17. 74. 43.]
 [46. 98. 51. 22. 98. 41. 66.]
 [39. 49. 56. 15. 53. 96. 99.]] 

[[ -5.43  18.57   7.57   4.57   8.57 -38.43   4.57]
 [-46.29  46.71 -41.29  48.71 -30.29  26.71  -4.29]
 [-14.29  37.71  -9.29 -38.29  37.71 -19.29   5.71]
 [-19.14  -9.14  -2.14 -43.14  -5.14  37.86  40.86]]


**Задача 4.**

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [128]:
def switch_signs(arr):
    return np.where(np.logical_and(3 < arr, arr < 8), -arr, arr)

a = np.array([5, 2, 4, 1, 3, -1])
print(a, "\n", switch_signs(a), "\n")

a = np.array([[6, 4], [-5, 9]])
print(a, "\n", switch_signs(a))

[ 5  2  4  1  3 -1] 
 [-5  2 -4  1  3 -1] 

[[ 6  4]
 [-5  9]] 
 [[-6 -4]
 [-5  9]]


**Задача 4.**

Написать функцию, принимающую на вход массив и вычитающую среднее из каждой строки в матрице. Протестировать на нескольких заданных вами примерах.

In [172]:
def substr_mean(arr):
    mean = 0
    columns = arr.shape[1]
    for i in range(0, columns):
        mean = round(arr[i].mean(), 2)
        if (arr.ndim > 1):
            arr[i] -= mean
        else:
            arr -= mean

    return arr

a = np.array([[6, 4], [-5, 8]], float)
print(f"Original arr:\n{a}")
print(f"Changed arr:\n{substr_mean(a)}\n")

a = np.array([[-6, 6, 1.4], [-1.5, 8.5, 0], [-9, 4, 0]], float)
print(f"Original arr:\n{a}")
print(f"Changed arr:\n{substr_mean(a)}")

Original arr:
[[ 6.  4.]
 [-5.  8.]]
Changed arr:
[[ 1.  -1. ]
 [-6.5  6.5]]

Original arr:
[[-6.   6.   1.4]
 [-1.5  8.5  0. ]
 [-9.   4.   0. ]]
Changed arr:
[[-6.47  5.53  0.93]
 [-3.83  6.17 -2.33]
 [-7.33  5.67  1.67]]


**Задача 5.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [32]:
n = np.array([1,2,3,4,5])
zeros = 3

new = np.zeros(len(n) + (len(n)-1)*(zeros))
new[::zeros+1] = n
print(new)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**Задача 6.**


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [181]:
def swap_strings(arr):
    rng = np.random.default_rng()
    x = rng.integers(0, arr.shape[1])
    y = x 
    
    while (x == y):
        y = rng.integers(0, arr.shape[1])

    arr[x], arr[y] = arr[y].copy(), arr[x].copy()

    return arr

a = np.array([[6, 4], [-5, 8]], float)
print(f"Original arr:\n{a}")
print(f"Changed arr:\n{swap_strings(a)}\n")

a = np.array([[-6, 6, 1.4], [-1.5, 8.5, 0], [-9, 4, 0]], float)
print(f"Original arr:\n{a}")
print(f"Changed arr:\n{swap_strings(a)}")


a = np.array([[-5, 1, 1], [4.54, 8.5, 2.43], [7, 11, -5], [9, 6, -4], [1, 8, 1]], float)
print(f"Original arr:\n{a}")
print(f"Changed arr:\n{swap_strings(a)}")

Original arr:
[[ 6.  4.]
 [-5.  8.]]
Changed arr:
[[-5.  8.]
 [ 6.  4.]]

Original arr:
[[-6.   6.   1.4]
 [-1.5  8.5  0. ]
 [-9.   4.   0. ]]
Changed arr:
[[-1.5  8.5  0. ]
 [-6.   6.   1.4]
 [-9.   4.   0. ]]
Original arr:
[[-5.    1.    1.  ]
 [ 4.54  8.5   2.43]
 [ 7.   11.   -5.  ]
 [ 9.    6.   -4.  ]
 [ 1.    8.    1.  ]]
Changed arr:
[[ 4.54  8.5   2.43]
 [-5.    1.    1.  ]
 [ 7.   11.   -5.  ]
 [ 9.    6.   -4.  ]
 [ 1.    8.    1.  ]]


**Задача 7.**


Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [196]:
def frequency(arr):
    values, counts = np.unique(a, return_counts=True)

    ind = np.argmax(counts)
    return values[ind], counts.max()
    print(values[ind]) 
    print(counts.max())

a = np.array([1,2,3,1,2,1,1,4,3,2,2,3])
print(f"Pair (value, frequency): {frequency(a)}")

a = np.array([5,2,3,1,5,1,5,1,5, 5, 5, 4,5])
print(f"Pair (value, frequency): {frequency(a)}")


Pair (value, frequency): (1, 4)
Pair (value, frequency): (5, 7)


**Задача 8.** 

Написать функцию, принимающую на вход  массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [235]:
SIZE = 16

def square_sum(arr):
    for i in range (0, 16, 4):
        for j in range(0, 16, 4):
            print(np.sum(a[i:i+4:,j:j+4:]), end=' ')
        print()

rng = np.random.default_rng()
a = np.round(np.random.rand(16, 16) * rng.integers(10, 50))
print(a)
square_sum(a)


[[ 0. 27.  7. 22.  6. 20.  1.  4. 26. 30.  2. 11. 25. 25. 19. 16.]
 [ 4. 19. 32. 17.  2. 25.  6.  6. 16. 12. 16. 21. 14. 16. 12. 18.]
 [23. 11.  5.  8.  6. 24. 20. 15. 27. 15. 32. 21. 30.  9. 30. 12.]
 [22. 17. 11. 21.  6. 13.  5.  3.  6. 22.  0.  7. 23. 20. 28. 26.]
 [27. 18. 21. 31. 31.  8. 23.  6.  7.  7. 18. 29. 13.  8. 22. 29.]
 [19.  9. 26. 11. 30.  4.  7.  3.  6. 25. 28. 15. 14.  2.  7. 25.]
 [16. 21.  3. 13.  0. 25.  4. 25.  1. 16.  1. 13. 31. 25.  5. 10.]
 [20. 18.  8. 10. 10. 28.  4. 14.  3. 19. 11. 21. 30. 27. 32. 30.]
 [ 5.  6.  2. 12. 19. 27. 32. 24. 22. 19. 12.  7. 21. 14. 28. 10.]
 [10.  8. 13.  3. 14. 24. 23.  2.  6. 32. 13.  7. 17. 24. 27. 22.]
 [18.  9.  9.  6.  1. 19.  4. 24. 31. 23.  7.  6. 19.  7. 13. 29.]
 [16.  3. 26. 31.  7. 11. 25. 26. 22. 29.  9.  7. 28. 26. 20.  4.]
 [26. 24.  6. 18. 19.  2.  9. 18. 10. 28. 16.  3.  1. 22.  5. 29.]
 [29. 29. 27.  1. 29. 26.  6. 18. 28. 20. 26. 31. 25.  3. 11. 29.]
 [18.  9.  4. 19. 23. 16.  2. 15. 23.  8. 14.  0. 26.  8.  4. 

**Задача 9.**

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [240]:
def max_values(arr, n):
    ind = np.argpartition(arr, -n)[-n:]
    return arr[ind]

n = int(input("Please enter the amount of largest numbers you would like to receive: "))
a = np.round(np.random.rand(n + 5) * rng.integers(0, 20))
print(a)
print(max_values(a, n))

[ 9.  4. 15. 10. 11.  3.]
[15.]


**Задача 10.**

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [260]:
def unequal_values(arr):
    new_arr = np.array([])

    for i in range(0, 10):
        if (np.unique(arr[i]).shape[0] > 1):
            new_arr = np.append(new_arr, arr[i], axis=0)

    n = len(new_arr) // 3

    new_arr = new_arr.reshape(n, 3)

    return new_arr

a = np.array([
    [1, 2, 3],
    [1, 1, 1],
    [2, 2, 3],
    [5, 7, 3],
    [6, 6, 6],
    [8, 8, 8],
    [1, 0, 0],
    [0, 0, 0],
    [3, 2, 3],
    [2, 2, 2]
])

print(unequal_values(a))

[1 2 3]
[2 3]
[3 5 7]
[0 1]
[2 3]
[[1. 2. 3.]
 [2. 2. 3.]
 [5. 7. 3.]
 [1. 0. 0.]
 [3. 2. 3.]]


**Задача 11.**

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

In [6]:
def unique_strings(arr):
    return np.unique(arr, axis = 0)

a = np.array([
    [3, 2, 3],
    [1, 1, 1],
    [3, 2, 3],
    [5, 7, 3],
    [6, 6, 6],
    [8, 8, 8],
    [1, 0, 0],
    [1, 0, 0],
    [3, 2, 3],
    [2, 2, 2]
])

print(unique_strings(a))

[[1 0 0]
 [1 1 1]
 [2 2 2]
 [3 2 3]
 [5 7 3]
 [6 6 6]
 [8 8 8]]


**Задача 12.**

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

In [10]:
def vector_distance(vec1, vec2):
    return np.dot(vec1, vec2)

v1 = np.array([5, 2, 4])
v2 = np.array([3.2, -1, 0])

print(vector_distance(v1, v2))

14.0


**Задача 13.**

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

In [11]:
def vector_cos(vec1, vec2):
    c = np.dot(vec1, vec2) / np.linalg.norm(vec1)/ np.linalg.norm(vec2) # -> cosine of the angle
    return np.arccos(np.clip(c, -1, 1))

v1 = np.array([5, 2, 4])
v2 = np.array([3.2, -1, 0])

print(f"Cos: {vector_cos(v1, v2)}")

Cos: 0.898864608756334


**Задача 14.**

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

 Протестировать на нескольких заданных вами примерах.


In [16]:
global Z 
def round_vector(arr):
    Z = np.where(arr >= 0.0, np.ceil(arr), np.trunc(arr))

v = np.array([3.5, -4.1, -2.99, 3.17, 14.90, 2.00001, -1.00000001], float)
print(v)
round_vector(v)
print(Z)

[ 3.5        -4.1        -2.99        3.17       14.9         2.00001
 -1.00000001]
[ 4. -4. -2.  4. 15.  3. -1.]


**Задача 15.**

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

 Протестировать на нескольких заданных вами примерах.

In [29]:
def same_values(vec1, vec2):
    global Z 
    Z = np.intersect1d(vec1, vec2)

v1 = np.array([1, 2, 5, 7, 8, 10, 12, 15])
v2 = np.array([1, 5, 10, 15, 22, 24, 41])

same_values(v1, v2)
print(Z)

v1 = np.array([1, 2, 5, 7])
v2 = np.array([15, 22, 24, 41])

same_values(v1, v2)
print(Z)

[ 1  5 10 15]
[]


**Задача 16.**

Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [30]:
def max_after_zero(arr):
    return np.max(arr[1:][(arr==0)[:-1]])

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

print(max_after_zero(x))

5


**Задача 17.**

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```

In [37]:
def longest_vector(arr):
    length = 0.0
    vec = np.array([])
    safe = 0.0
    for i in range(0, 5):
        safe = np.linalg.norm(arr[i])
        if (safe > length):
            length = safe
            vec = arr[i]

    return vec, length

arr = np.array( [
    [1, 2, 3],
    [1, -0.2, 13],
    [4.2, -5, 6],
    [3.2, -1.2, 8],
    [10, -2, 4.3]
])

print(longest_vector(arr))


arr = np.array( [
    [1, -2, 5],
    [4.12, -0.2, 1],
    [-4.2, -0.68, 4.21],
    [3.2, -1.2, 1.8],
    [-2.32, 7.12, 3.333]
])

print(longest_vector(arr))

(array([ 1. , -0.2, 13. ]), 13.03993865016243)
(array([-2.32 ,  7.12 ,  3.333]), 8.196687684668728)
